# Generated by Django 4.1.5 on 2023-03-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='icon',
            new_name='media_image',
        ),
        migrations.AddField(
            model_name='education',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
