# Generated by Django 4.1.5 on 2023-01-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
