# Generated by Django 4.1.5 on 2023-03-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_icon_media_media_image_education_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
