# Generated by Django 4.1.5 on 2023-04-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='educationdegree',
            name='degree',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='as_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='work_place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type',
            field=models.CharField(max_length=200),
        ),
    ]
