# Generated by Django 4.1.5 on 2023-04-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_education_faculty_alter_education_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='knowledge_extent',
            field=models.CharField(choices=[('--de A1 ||| --en A1 ||| --ru A1 ||| --uz A1', '--de A1 ||| --en A1 ||| --ru A1 ||| --uz A1'), ('--de A2 ||| --en A2 ||| --ru A2 ||| --uz A2', '--de A2 ||| --en A2 ||| --ru A2 ||| --uz A2'), ('--de B1 ||| --en B1 ||| --ru B1 ||| --uz B1', '--de B1 ||| --en B1 ||| --ru B1 ||| --uz B1'), ('--de B2 ||| --en B2 ||| --ru B2 ||| --uz B2', '--de B2 ||| --en B2 ||| --ru B2 ||| --uz B2'), ('--de C1 ||| --en C1 ||| --ru C1 ||| --uz C1', '--de C1 ||| --en C1 ||| --ru C1 ||| --uz C1'), ('--de Einheimisch ||| --en Native ||| --ru Родной ||| --uz Mahalliy', '--de Einheimisch ||| --en Native ||| --ru Родной ||| --uz Mahalliy')], max_length=70),
        ),
    ]
