# Generated by Django 4.1.5 on 2023-03-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_language_comment_media_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='ended',
            field=models.DateField(null=True),
        ),
    ]
