# Generated by Django 4.1.5 on 2023-01-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_resume_link_alter_contactdetail_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='full_bio',
        ),
        migrations.AddField(
            model_name='about',
            name='short_bio',
            field=models.TextField(null=True),
        ),
    ]
