# Generated by Django 4.1.5 on 2023-04-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_language_knowledge_extent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
