# Generated by Django 4.1.5 on 2023-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_text_about_full_bio_about_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_finished',
            field=models.DateField(null=True),
        ),
    ]
