# Generated by Django 4.1.5 on 2023-03-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_programminglanguage_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='comment',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='is_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='is_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='value',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
