# Generated by Django 4.1.5 on 2023-02-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_date_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='media',
            name='icon',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
