# Generated by Django 4.1.5 on 2023-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_about_avatar_alter_media_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_created',
            field=models.CharField(choices=[('My own', 'My own'), ('With team', 'With team')], max_length=100, null=True),
        ),
    ]
