# Generated by Django 4.1.5 on 2023-02-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_about_lang_contactdetail_lang_project_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='about',
            name='programming_languages',
            field=models.ManyToManyField(null=True, related_name='programming_languages', to='main.programminglanguage'),
        ),
    ]
