# Generated by Django 4.1.5 on 2023-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_about_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='programming_languages',
            field=models.ManyToManyField(to='main.programminglanguage'),
        ),
    ]
