# Generated by Django 4.1.5 on 2023-02-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_about_programming_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='education',
        ),
        migrations.RemoveField(
            model_name='about',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='about',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='about',
            name='education',
            field=models.ManyToManyField(to='main.education'),
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.ManyToManyField(to='main.language'),
        ),
        migrations.AddField(
            model_name='about',
            name='work_experience',
            field=models.ManyToManyField(to='main.workexperience'),
        ),
    ]
