# Generated by Django 4.1.5 on 2023-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_about_education_remove_about_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(choices=[('Associate degree', 'Associate degree'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree'), ('Специализирования', 'Специализирования'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Докторантура', 'Докторантура'), ("O'rta maxsus", "O'rta maxsus"), ('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Doktorlik', 'Doktorlik')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='knowledge_extent',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('Native', 'Native'), ('Родной язык', 'Родной язык'), ('Ona til', 'Ona til')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(choices=[('Remote full-time', 'Remote full-time'), ('Remote part-time', 'Remote part-time'), ('Remote contract', 'Remote contract'), ('In-person full-time', 'In-person full-time'), ('In-person part-time', 'In-person part-time'), ('In-person contract', 'In-person contract'), ('Freelance', 'Freelance'), ('Удалено, на полный рабочий день', 'Удалено, на полный рабочий день'), ('Удаленно, частичная занятость', 'Удаленно, частичная занятость'), ('Удаленно, контракт', 'Удаленно, контракт'), ('На полный рабочий день, в офисе', 'На полный рабочий день, в офисе'), ('Частичная занятость, в офисе', 'Частичная занятость, в офисе'), ('Контракт, в офисе', 'Контракт, в офисе'), ('Фриланс', 'Фриланс'), ("Masofaviy, to'liq vaqt", "Masofaviy, to'liq vaqt"), ('Masofaviy, yarim kunlik', 'Masofaviy, yarim kunlik'), ('Masofaviy, shartnoma asosida', 'Masofaviy, shartnoma asosida'), ("Ofisda, to'liq vaqt", "Ofisda, to'liq vaqt"), ('Ofisda, yarim kunlik', 'Ofisda, yarim kunlik'), ('Ofisda, shartnoma asosida', 'Ofisda, shartnoma asosida'), ('Mustaqil (Frilans)', 'Mustaqil (Frilans)')], max_length=100),
        ),
    ]
