# Generated by Django 4.1.5 on 2023-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_education_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='contactdetail',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lang',
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(choices=[('Associate degree', 'Associate degree'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='knowledge_extent',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('Native', 'Native')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(choices=[('Remote full-time', 'Remote full-time'), ('Remote part-time', 'Remote part-time'), ('Remote contract', 'Remote contract'), ('In-person full-time', 'In-person full-time'), ('In-person part-time', 'In-person part-time'), ('In-person contract', 'In-person contract'), ('Freelance', 'Freelance')], max_length=100),
        ),
    ]
